stages:
  - setup
  - recommend
  - deploy

test:
  stage: setup
  script:
    - pip install -r requirements.txt
    - pytest

recommend:
  stage: build
  script:
    - pip install mlflow
    - python recommend.py
    - python recommend.py
deploy:
  stage: deploy
  script:
    - apt-get update -y
    - apt-get install -y docker.io
    - docker build -t my-recommendation-system .
    - docker run -d -p 5001:5000 my-recommendation-system
watch:
  stage: watch
  script:
    - apt-get update -y
    - apt-get install -y inotify-tools
    - pip install watchdog
    - nohup python file_watcher.py &
